const express = require("express");

const router = express.Router();

const pendingTasks = [
    {
        cod_trabajo: "J001",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J002',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J003',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: "J004",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J005',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J006',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: "J007",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J008',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J009',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: "J010",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J011',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J012',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: "J013",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J014',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J015',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: "J016",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J017',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J018',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: "J019",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J020',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J021',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: "J022",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J023',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J024',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: "J025",
        categoria: "Carpintería",
        descripcion: "Construcción de armario",
        fec_ini: '2022-01-01',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: 'J026',
        categoria: 'Fontanería',
        descripcion: 'Reparación de tuberías',
        fec_ini: '2022-01-02',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: 'J027',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: 'J028',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: 'J029',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
    {
        cod_trabajo: 'J030',
        categoria: 'Electricidad',
        descripcion: 'Instalación de luces',
        fec_ini: '2022-01-03',
        fec_fin: null,
        tiempo: null,
        id_trabajador: 'T003',
        prioridad: 3,
    },
];

const completedTasks = [
    {
        cod_trabajo: "J031",
        categoria: "Carpintería",
        descripcion: "Construcción de mesa",
        fec_ini: '2022-01-24',
        fec_fin: '2022-01-26',
        tiempo: 10.0,
        id_trabajador: 'T001',
        prioridad: 1,
    },
    {
        cod_trabajo: "J032",
        categoria: "Fontanería",
        descripcion: "Cambiar grifo",
        fec_ini: '2022-01-24',
        fec_fin: '2022-01-28',
        tiempo: 26.0,
        id_trabajador: 'T002',
        prioridad: 2,
    },
    {
        cod_trabajo: "J033",
        categoria: "Jardineria",
        descripcion: "Regar el jardín",
        fec_ini: '2022-07-12',
        fec_fin: '2022-07-13',
        tiempo: 9.0,
        id_trabajador: 'T003',
        prioridad: 3,
    },
];

router.get("/pending", (req, res) => {
    res.status(200).send({ result: pendingTasks });
});

router.get("/pending/:id", (req, res) => {
    const id = req.params.id;
    const task = pendingTasks.filter(t => t.cod_trabajo == id)[0];
    res.status(200).send({ result: task });
});

router.get("/completed", (req, res) => {
    res.status(200).send({ result: completedTasks });
});

router.get("/completed/:id", (req, res) => {
    const id = req.params.id;
    const task = completedTasks.filter(t => t.cod_trabajo == id)[0];
    res.status(200).send({ result: task });;
});

module.exports = router;
